### ISSUE TITLE
UnboundLocalError: local variable 'sample_ent2pair' referenced before assignment

### ISSUE THREAD

**Issue by kyanaww** [zhiweihu1103/ET-TET#3]
When I try to test on YAGO43kET, it comes out：
Traceback (most recent call last):
  File "./run.py", line 216, in <module>
    main(params)
  File "./run.py", line 67, in main
    type_predict = model(sample_et_content, sample_kg_content, sample_ent2pair)
UnboundLocalError: local variable 'sample_ent2pair' referenced before assignment
Traceback (most recent call last):
  File "./run.py", line 216, in <module>
    main(params)
  File "./run.py", line 67, in main
    type_predict = model(sample_et_content, sample_kg_content, sample_ent2pair)
UnboundLocalError: local variable 'sample_ent2pair' referenced before assignment

How can I fix it？

**Comment by zhiweihu1103** [comment]
I guess you didn't set the **--cuda** parameter?

**Comment by kyanaww** [comment]
I use the
CUDA_VISIBLE_DEVICES=0 python -u ./run.py --dataset YAGO43kET --save_path YAGO43kET --hidden_dim 100 --temperature 0.5 --lr 0.001  --train_batch_size 128 --cuda 11.0 --max_epoch 500 --valid_epoch 25 --beta 1 --loss SFNA   --pair_pooling avg --sample_et_size 3 --sample_kg_size 8 --sample_ent2pair_size 6 --warm_up_steps 50   --tt_ablation all   > ./logs/YAGO43kET.out 2>&1 &
maybe I use in the wrong way？

**Comment by zhiweihu1103** [comment]
You shouldn't add 11.0.

CUDA_VISIBLE_DEVICES=0 python -u ./run.py --dataset YAGO43kET --save_path YAGO43kET --hidden_dim 100 --temperature 0.5 --lr 0.001 --train_batch_size 128 **--cuda** --max_epoch 500 --valid_epoch 25 --beta 1 --loss SFNA --pair_pooling avg --sample_et_size 3 --sample_kg_size 8 --sample_ent2pair_size 6 --warm_up_steps 50 --tt_ablation all > ./logs/YAGO43kET.out 2>&1 &

**Comment by kyanaww** [comment]
I delete the 11.0, it still get the same error
![image](https://user-images.githubusercontent.com/75066115/201321444-ac4233a2-1c10-40cb-bbf4-03e98c65b5e1.png)

**Comment by zhiweihu1103** [comment]
So strange, this error only occurs when the --cuda parameter is not set, as shown in the following code.
https://github.com/zhiweihu1103/ET-TET/blob/18bf33362b48313aadbf752a0ca731c8efa3579e/run.py#L21

**Comment by kyanaww** [comment]
I solved it by replace pytorch（CPU）with GPU version, thanks for your tips
